// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientAmountDTO } from "./IngredientAmountDTO";
import type { ServingsTypeDTO } from "./ServingsTypeDTO";

export interface CreateRecipeDTO { name: string, description: string, steps: Array<string>, time: Record<string, bigint>, ingredients: Array<IngredientAmountDTO>, servings: ServingsTypeDTO, }