// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateRecipeIngredient } from "./CreateRecipeIngredient";

export interface CreateRecipeDTO { name: string, description: string, serves: number, ingredients: Array<CreateRecipeIngredient>, steps: Array<string>, }