// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IngredientUnitDTO = { "_type": "mililiters", "amount": number } | { "_type": "grams", "amount": number } | { "_type": "teaspoons", "amount": number } | { "_type": "cups", "amount": number } | { "_type": "other", "amount": { amount: number, unit: string, } };