// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientUnitDTO } from "./IngredientUnitDTO";

export interface IngredientAmountDTO { ingredient_id: string, amount: IngredientUnitDTO, optional: boolean, notes: string | null, }