// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IngredientUnitDTO = { "mililiters": number } | { "grams": number } | { "teaspoons": number } | { "cups": number } | { "other": { amount: number, unit: string, } };