// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientDTO } from "./IngredientDTO";
import type { IngredientUnitDTO } from "./IngredientUnitDTO";

export interface IngredientWithAmountDTO { ingredient: IngredientDTO, amount: IngredientUnitDTO, optional: boolean, notes: string | null, }