// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientWithAmount } from "./IngredientWithAmount";

export interface RecipeDTO { id: number, name: string, description: string, serves: number, ingredients: Array<IngredientWithAmount>, steps: Array<string>, }