// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateIngredientDTO { name?: string, description?: string, diet_violations?: Array<string>, }