// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServingsTypeDTO } from "./ServingsTypeDTO";

export interface UpdateRecipeDTO { name: string | null, description: string | null, steps: Array<string> | null, time: Record<string, bigint> | null, servings: ServingsTypeDTO | null, }