[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./styles/tailwind.css -o ./dist/.stage/index.css"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx esbuild ./src-ts/index.ts --outfile=./dist/.stage/index.js"]

[[proxy]]
rewrite = "/api"
backend = "http://localhost:8111"
