[watch]
ignore = ["compiled-js"]

[[hooks]]
stage = "post_build"
command = "npm"
command_arguments = ["run", "build:css"]

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build:js"]

[[proxy]]
rewrite = "/api"
backend = "http://localhost:8111"
