[settings]
env_file = ".env"

[tools]
node = "20"
task = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:mprocs" = "latest"
httpie-go = "latest"
hurl = "latest"
caddy = "latest"
