---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  backend: ./.taskfiles/Backend/Taskfile.yaml

tasks:
  default: task -l
  db:prepare:
    desc: "Prepare SQLx for offline"
    cmd: cargo sqlx prepare --workspace -- --tests
  db:migrate:
    desc: "Run every migration"
    cmds:
      - task: backend:migrate
  db:check:
    desc: "Check if SQLx prepared files are generated"
    cmd: cargo sqlx prepare --workspace --check -- --tests
  test:
    desc: "Testing the application"
    cmd: "cargo nextest run"
    env:
      SQLX_OFFLINE: true
  test:coverage:
    desc: "Test the application (with coverage)"
    cmd: "cargo llvm-cov nextest"
    env:
      SQLX_OFFLINE: true
