---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  backend: 
    taskfile: ./.taskfiles/Backend/Taskfile.yaml
    aliases:
      - be
  frontend:
    taskfile: ./.taskfiles/Frontend/Taskfile.yaml
    aliases:
      - fe
tasks:
  default: task -l
  db:prepare:
    desc: "Prepare SQLx for offline"
    cmd: cargo sqlx prepare --workspace -- --tests
  db:migrate:
    desc: "Run every migration"
    cmds:
      - task: backend:migrate
  db:check:
    desc: "Check if SQLx prepared files are generated"
    cmd: cargo sqlx prepare --workspace --check -- --tests
  test:
    desc: "Testing the application"
    cmd: "cargo nextest run"
    env:
      SQLX_OFFLINE: true
  test:coverage:
    desc: "Test the application (with coverage)"
    cmd: "cargo llvm-cov nextest"
    env:
      SQLX_OFFLINE: true
  test:coverage:ci:
    desc: "Test the application (with coverage; export to LCOV for CodeCov)"
    cmd: "cargo llvm-cov nextest --lcov --output-path lcov.info"
    env:
      SQLX_OFFLINE: true
  unused:
    desc: "Check for unused dependencies"
    cmds:
      - task: backend:unused
      - task: frontend:unused
  frontend:unused:
    desc: "Check for unused dependencies on the frontend"
    cmd: "npx knip"
    dir: "frontend"
    ignore_error: true
