[package]
name = "backend"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.79"
axum = { version = "0.7.5", features = ["multipart"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
