---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  migrate:
    desc: "[BACKEND] run database migration"
    cmd: cargo sqlx migrate run
    dir: backend
  unused:
    desc: "[BACKEND] Check for unused dependencies"
    cmd: "cargo +nightly udeps --all-targets"
    ignore_error: true
  dev:
    desc: "[BACKEND] start development server"
    cmd: bacon run
