---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  migrate:
    desc: "[BACKEND] run database migration"
    cmd: cargo sqlx migrate run
    dir: backend
  unused:
    desc: "[BACKEND] Check for unused dependencies"
    cmd: "cargo +nightly udeps --all-targets"
    ignore_error: true
  dev:
    desc: "[BACKEND] start development server"
    cmd: bacon run
  install:
    desc: "[BACKEND] install dependencies"
    cmd: "cargo fetch"
    aliases:
      - i
      - deps
  lint:
    desc: "[BACKEND] run linters"
    cmds:
      - task: clippy
      - task: fmt
  lint:fix:
    desc: "[BACKEND] fix linting errors"
    cmds:
      - task: clippy
      - task: fmt:fix
  clippy:
    desc: "[BACKEND] run cargo-clippy"
    cmd: "cargo clippy"
  fmt:
    desc: "[BACKEND] run cargo-fmt in check mode"
    cmd: "cargo fmt --check"
  fmt:fix:
    desc: "[BACKEND] run cargo-fmt"
    cmd: "cargo fmt"
