CREATE TABLE IF NOT EXISTS recipes (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  description TEXT NOT NULL,
  user_id integer NOT NULL,
  CONSTRAINT recipes_fk_users
    FOREIGN KEY(user_id) 
    REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE TABLE ingredients (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients_in_recipes (
  recipe_id integer NOT NULL,
  ingredient_id integer NOT NULL,
  unit varchar(20) NOT NULL,
  amount FLOAT NOT NULL,
  PRIMARY KEY (recipe_id, ingredient_id),
  CONSTRAINT ingredients_in_recipes_fk_ingredients
    FOREIGN KEY (ingredient_id)
    REFERENCES ingredients (id)
    ON DELETE RESTRICT,
  CONSTRAINT ingredients_in_recipes_fk_recipes
    FOREIGN KEY (recipe_id)
    REFERENCES recipes (id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS steps (
  "index" integer NOT NULL,
  "recipe_id" integer NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  "instructions" TEXT NOT NULL,
  PRIMARY KEY (index, recipe_id)
);
